sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera_top/camera/depth_registered/points
    filtered_cloud_topic: /camera_top/arm_filtered_cloud
    max_range: 2.0
    point_subsample: 1
    shape_padding: 0.01
    shape_scale: 1.0
    padding_scale: 1.2
    padding_offset: 0.10
